apiVersion: v1
kind: ConfigMap
metadata:
  name: http_check-configmap
data:
  URLS: "https://httpstat.us/503,https://httpstat.us/200"
  TIMEOUT: "2"
  PORT: "8090"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: http_check-deploy
  labels:
    app: http_check-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: http_check
  template:
    metadata:
      labels:
        app: http_check
    spec:
      containers:
      - name: http_check
        image: himadriganguly/sample_external_url
        env:
        - name: URLS
          valueFrom:
            configMapKeyRef:
              name: http_check-configmap
              key: URLS
        - name: TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: http_check-configmap
              key: TIMEOUT
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: http_check-configmap
              key: PORT

---
apiVersion: v1
kind: Service
metadata:
  name: http_check-service
spec:
  selector:
    app: http_check
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8090
